[workspace]
resolver = "2"
members = [
    "cubeb-core",
    "cubeb-api",
    "cubeb-backend",
    "cubeb-sys",
    "systest",
    "xtask",
]
exclude = [
  "cubeb-sys/libcubeb/src/cubeb-coreaudio-rs",
  "cubeb-sys/libcubeb/src/cubeb-pulse-rs",
]
