[package]
name = "systest"
version = "0.1.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
build = "build.rs"
edition = "2018"

[features]
gecko-in-tree = ["cubeb-sys/gecko-in-tree"]

[dependencies]
cubeb-sys = { path = "../cubeb-sys" }
libc = "0.2"

[build-dependencies]
ctest2 = "0.4"
